package edu.cuny.hunter.streamrefactoring.core.analysis;

public enum Refactoring {
	CONVERT_SEQUENTIAL_STREAM_TO_PARALLEL,
	CONVERT_NONCONCURRENT_COLLECTOR_TO_CONCURRENT,
	CONVERT_CONCURRENT_COLLECTOR_TO_NONCONCURRENT,
	CONVERT_PARALLEL_STREAM_TO_SEQUENTIAL,
	OPTIMIZE_PARALLEL_STREAM
}
